# Generated by Django 5.0

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='inventory.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InfoSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='info_systems', to='inventory.stream')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=255, unique=True)),
                ('cpu', models.PositiveIntegerField(default=1)),
                ('ram', models.PositiveIntegerField(default=1)),
                ('disk', models.PositiveIntegerField(default=10)),
                ('instance', models.PositiveSmallIntegerField(default=1)),
                ('tags', models.JSONField(default=list)),
                ('info_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vms', to='inventory.infosystem')),
            ],
            options={
                'ordering': ['instance', 'fqdn'],
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolVM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_vms', to='inventory.pool')),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_vms', to='inventory.vm')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('pool', 'vm')},
            },
        ),
        migrations.AddConstraint(
            model_name='vm',
            constraint=models.CheckConstraint(check=models.Q(('instance__gte', 1), ('instance__lte', 20)), name='instance_1_20'),
        ),
    ]
