# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='infosystem',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
