# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_department_short_name_infosystem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosystem',
            name='is_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
