# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_infosystem_is_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='ip',
            field=models.CharField(default='000.000.000.000', max_length=15),
        ),
        migrations.AddField(
            model_name='poolvm',
            name='original_tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
