# Generated by Django 5.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_vm_ip_poolvm_original_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='cpu_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='ram_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='disk_quota',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
