# Generated by Django 5.x on 2026-03-20 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('inventory', '0010_userprofile_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='VMRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление')], max_length=10)),
                ('request_number', models.CharField(blank=True, default='', max_length=255)),
                ('contractor_task_number', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('vm', models.ForeignKey(on_delete=models.CASCADE, related_name='requests', to='inventory.vm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
